# Generated by Django 4.2.30 on 2026-06-02 19:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('soni', models.IntegerField(default=0, verbose_name='Umumiy soni')),
                ('narxi', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="Narxi (so'm)")),
                ('sotildi', models.IntegerField(default=0, verbose_name='Sotildi')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-yaratilgan'],
            },
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familiya', models.CharField(max_length=200, verbose_name='Ism Familiya')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('manzil', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-yaratilgan'],
            },
        ),
        migrations.CreateModel(
            name='Savdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('tolov_turi', models.CharField(choices=[('naqd', 'Naqd pul'), ('nasiya', 'Nasiya'), ('plastik', 'Plastik karta')], default='naqd', max_length=10, verbose_name="To'lov turi")),
                ('jami_summa', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Jami summa')),
                ('to_langan', models.BooleanField(default=True, verbose_name="To'langan")),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('mijoz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savdolar', to='crm.mijoz', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Savdo',
                'verbose_name_plural': 'Savdolar',
                'ordering': ['-yaratilgan'],
            },
        ),
        migrations.CreateModel(
            name='SavdoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField(default=1, verbose_name='Soni')),
                ('narxi', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Narxi')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.mahsulot', verbose_name='Mahsulot')),
                ('savdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savdo_itemlar', to='crm.savdo')),
            ],
            options={
                'verbose_name': 'Savdo element',
                'verbose_name_plural': 'Savdo elementlar',
            },
        ),
    ]
