# Generated by Django 5.2.15 on 2026-06-07 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='soni',
        ),
        migrations.RemoveField(
            model_name='mahsulot',
            name='sotildi',
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='qoldi',
            field=models.IntegerField(default=0, verbose_name='Qoldi (joriy)'),
        ),
        migrations.CreateModel(
            name='Kirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField(verbose_name='Kirim soni')),
                ('narxi', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Kirim narxi')),
                ('izoh', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
                ('sana', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kirimlar', to='crm.mahsulot', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Kirim',
                'verbose_name_plural': 'Kirimlar',
                'ordering': ['-yaratilgan'],
            },
        ),
    ]
